import torch
from transformers import (
    T5ForConditionalGeneration,
    RobertaTokenizer,
    AutoTokenizer,
    AutoModelForCausalLM
)

code_model_name = "Salesforce/codet5-small"
code_tokenizer = RobertaTokenizer.from_pretrained(code_model_name)
code_model = T5ForConditionalGeneration.from_pretrained(code_model_name)
code_model.eval()

explanation_model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
chat_tokenizer = AutoTokenizer.from_pretrained(explanation_model_name, use_fast=True)
chat_model = AutoModelForCausalLM.from_pretrained(explanation_model_name)
chat_model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
code_model.to(device)
chat_model.to(device)

def summarize_code_with_codet5(code: str, max_tokens: int = 64) -> str:
    """
    Summarizes the given code snippet using a CodeT5 model.

    This function takes a code snippet as input and generates a concise summary
    using a pre-trained CodeT5 model. The summary is generated by tokenizing the
    input code, feeding it into the model, and decoding the output tokens.

    Args:
        code (str): The code snippet to be summarized.
        max_tokens (int, optional): The maximum number of tokens for the generated
            summary. Defaults to 64.

    Returns:
        str: A summarized version of the input code.
    """
    prompt = f"summarize: {code}"
    inputs = code_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
    outputs = code_model.generate(
        **inputs,
        max_length=max_tokens,
        num_beams=4,
        early_stopping=True,
        no_repeat_ngram_size=2
    )
    return code_tokenizer.decode(outputs[0], skip_special_tokens=True).strip()

def build_prompt(code: str, summary: str, question: str) -> str:
    """
    Constructs a formatted prompt string for an AI model to provide explanations 
    and answers related to a given Python function.
    Args:
        code (str): The Python function code provided by the user.
        summary (str): A brief summary or description of the function's purpose.
        question (str): A specific question about the function that needs to be answered.
    Returns:
        str: A formatted string containing the instruction, code, summary, and question 
        to guide the AI model in generating a response.
    """

    return f"""### Instruction:
            You are an expert data structures and algorithms tutor. A user provides the following Python function and asks a question related to how it works.

            Code:
            {code}

            Summary:
            {summary}

            Question:
            {question}

            Please explain the code and answer the question in simple, beginner-friendly English.
            Avoid including raw code in your answer.

            ### Response:
            """

def generate_explanation_with_tinyllama(prompt: str, max_tokens: int = 256) -> str:
    """
    Generates a text explanation using the TinyLlama model based on the given prompt.
    Args:
        prompt (str): The input text prompt to guide the text generation.
        max_tokens (int, optional): The maximum number of tokens to generate. Defaults to 256.
    Returns:
        str: The generated explanation as a string, cleaned and formatted.
    """

    inputs = chat_tokenizer(prompt, return_tensors="pt").to(device)
    outputs = chat_model.generate(
        **inputs,
        max_new_tokens=max_tokens,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        pad_token_id=chat_tokenizer.eos_token_id
    )
    decoded = chat_tokenizer.decode(outputs[0], skip_special_tokens=False)
    return clean_response(decoded[len(prompt):].strip())

def clean_response(text: str) -> str:
    """
    Cleans the input text by removing specific substrings and stripping whitespace.
    This function performs the following operations on the input text:
    - Removes occurrences of "se:".
    - Removes occurrences of "</s>".
    - Strips leading and trailing whitespace.
    Args:
        text (str): The input string to be cleaned.
    Returns:
        str: The cleaned string after applying the transformations.
    """

    return (
        text.replace("se:", "")
            .replace("</s>", "")
            .strip()
    )

def generate_full_explanation(code: str, question: str) -> str:
    """
    Generates a detailed explanation for a given code snippet and question.
    This function takes a code snippet and a related question as input, summarizes
    the code using a CodeT5 model, builds a prompt using the summary and question,
    and generates a detailed explanation using a TinyLlama model.
    Args:
        code (str): The code snippet to be analyzed and explained.
        question (str): The question related to the code snippet.
    Returns:
        str: A detailed explanation generated based on the code and question.
    """

    summary = summarize_code_with_codet5(code)
    prompt = build_prompt(code, summary, question)
    explanation = generate_explanation_with_tinyllama(prompt)
    return explanation
